import Navbar from '@/components/Navbar';
import './globals.css';
import Providers from './Providers';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/context/auth.context';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={` flex flex-col bg-black text-white antialiased`}>
        <div className="top">
          <Providers>
            <Navbar />
          </Providers>
        </div>
        <div className="bottom flex justify-between w-full  i">
          <div className="left w-['20vw'] "></div>
          <div className="right w-full mt-4 ">
            <AuthProvider>
              <Providers>{children}</Providers>
            </AuthProvider>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
