import Navbar from '@/components/Navbar';
import './globals.css';
import { islogin } from '../../appConfig';
import { redirect } from 'next/navigation';
import Sidebar from '@/components/Sidebar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true" className={`  bg-black text-white antialiased`}>
        <Navbar />
        {/* <Sidebar /> */}
        {children}
      </body>
    </html>
  );
}
